# Identificación del proyecto en SonarCloud
sonar.organization=williamrcr
sonar.projectKey=WilliamRCR_EjSonar
sonar.projectName=EjSonar - Ejemplo Python

#Código fuente y pruebas
sonar.sources=src,app.py
sonar.tests=tests
sonar.python.version=3.12

#Cobertura (reporte generado por pytest --cov)
sonar.python.coverage.reportPaths=coverage.xml

#Exclusiones de cobertura
sonar.coverage.exclusions=tests/**,app.py

#Codificación
sonar.sourceEncoding=UTF-8
